### ISSUE TITLE
Prettier formatting breaks generated types (queries)

### ISSUE THREAD

**Issue by phillipgajadhar** [mmkal/slonik-tools#148]
prettier.config.json:

> module.exports = {
>    trailingComma: "es5",
>    tabWidth: 4,
>    semi: true,
>    singleQuote: true
> };

Top-most stacktrace error:

> "SyntaxError: Unexpected end of JSON input",
>             "    at JSON.parse (<anonymous>)",
>             "    at .../@slonik/typegen/src/index.ts:231:49",

**Comment by mmkal** [comment]
Is this when running prettier cli? If so, I recommend telling prettier to ignore generated files, example: https://github.com/mmkal/slonik-tools/blob/8d21fa0c79ba73eb31c666970767a23c48bd9d55/.prettierignore#L1

**Comment by phillipgajadhar** [comment]
Yes it is. Ignored
Cheers.
