### ISSUE TITLE
@slonik/migrator: .DS_Store does not match pattern

### ISSUE THREAD

**Issue by karlhorky** [mmkal/slonik-tools#172]
Maybe it would be possible to ignore certain auto-created files like `.DS_Store`?

![Screen Shot 2020-04-06 at 16 12 27](https://user-images.githubusercontent.com/1935696/78567864-99ee3300-7821-11ea-8334-6fbaf6751472.png)

**Comment by mmkal** [comment]
fix released in v0.3.2: https://www.npmjs.com/package/@slonik/migrator/v/0.3.2

**Comment by karlhorky** [comment]
Awesome, thanks!
