### ISSUE TITLE
Feature: Add ability to log when types should change, but don't write.

### ISSUE THREAD

**Issue by hcharley** [mmkal/slonik-tools#180]
This might be good for deployed testing environments, where you might want to keep an eye on if queries have drifted from development, but you don't want types to be generated.

**Comment by mmkal** [comment]
Not going to implement this. The typegen library has moved away from being a runtime dependency and become a CLI. I would recommend it only be run against non-production databases. But if you really want, you _could_ ignore that advice and see if you get any changes in the generated types against production.
