### ISSUE TITLE
migrator: ability to revert last batch of migrations

### ISSUE THREAD

**Issue by indeyets** [mmkal/slonik-tools#189]
I'm not sure if this feature is considered to be "in scope" by you. I can implement it myself, but it might be useful for a large amount of users and, maybe, it deserves to be mentioned in documentation.

[Knex's migrate-tool](https://knexjs.org/#Migrations) works like this: on each "up" it creates "migration group" record in database, which lists migrations applied during the session.

And default action of "down" is to revert last group of migrations. Second run will revert second-last group, etc.

This is really useful in blue-green deployment scenarios where we want to revert migrations in case when new version of application couldn't start

**Comment by indeyets** [comment]
I see manual implementation in deploy-tool to be like this:

1. parse list of applied migrations from "up" command
2. store it somewhere in ansible
3. try to start new version of app
4. if (3) fails, call "down" with stored named of migrations as parameters (see #188 for related issue)

**Comment by indeyets** [comment]
I see manual implementation in deploy-tool to be like this:

1. parse list of applied migrations from "up" command
2. store it somewhere in ansible
3. try to start new version of app
4. if (3) fails, call "down" with stored named of migrations as parameters (see #188 for related issue)

**Comment by mmkal** [comment]
I think this should be doable, yes. Just a note - the current behaviour for `node migrate down` is already what you describe - it only "undoes" the most recent migration. Running again undoes the second-most-recent.

But the other part of what you ask isn't currently supported - to pass a list of migrations to undo. You should be able to do something like `echo migration4 migration3 | xargs node migrate down` to achieve what you want, but I'll look into supporting it directly in the migrator.

At the very least, I agree that there should be more documentation around this.

**Comment by mmkal** [comment]
@indeyets I think the PR above should cover your use case. There are some new docs [in the readme too](https://github.com/mmkal/slonik-tools/tree/master/packages/migrator#controlling-migrations).
