### ISSUE TITLE
typegen: Question: Is it possible to cap the number of latest queries that is stored so that older queries get auto removed over time?

### ISSUE THREAD

**Issue by charlex** [mmkal/slonik-tools#195]

**Comment by mmkal** [comment]
Nope, this is currently not possible, but you can use the cli helper to wipe out all types from the generated directory:

```bash
npx slonik-typegen path/to/your/generated/directory
```

Then re-run your tests and only active queries will be re-created. Right now no extra information is stored other than the queries themselves, so there isn't a way of knowing how old they are.

**Comment by charlex** [comment]
@mmkal Thanks! I am only partially using my tests to generate types. I really need to switchover fully to having the tests generate the types.
