### ISSUE TITLE
typeMapper only accepts globally available types

### ISSUE THREAD

**Issue by Ericnr** [mmkal/slonik-tools#219]
Currently I need to declare global types if I want to map postgres `numeric` type to a `Decimal` class exported by a lib. We could have an api like `importTypes: 'process.cwd() + '/src/types/slonikTypes'` so that file is imported by every type gen file.

**Comment by mmkal** [comment]
@Ericnr you should be able to use `import`, something like:

```js
setupTypeGen({
  knownTypes,
  typeMapper: {
    numeric: [`import('../../decimal')`, toDecimal],
  },
})
```
