### ISSUE TITLE
Wrapping in transaction(s) for DBs that support it / SQL templating

### ISSUE THREAD

**Issue by t3hmrman** [mmkal/slonik-tools#283]
Some databases support DDL in transactions, and for those it's almost strictly better for migrations to be all-or-nothing, as in:

```sql
BEGIN TRANSACTION;

CREATE TABLE some_table (...);

CREATE INDEX some_table_idx (...);

COMMIT TRANSACTION;
```

It would be nice to have the created files have `BEGIN TRANSACTION` at the top for Postgres.

While the quick fix might be just adding the lines (maybe having them commented out), a more general one might be allowing the specification of a static template for up/down migration migrations, then I can just add the file, make sure to point to it in my config and then when I make a migration it will have the bits I want in it.

**Comment by mmkal** [comment]
@t3hmrman this is now possible in [v0.8](https://github.com/mmkal/slonik-tools/blob/master/packages/migrator/readme.md) using [singleTransaction](https://github.com/mmkal/slonik-tools/blob/8d7c4a2110db0caed64ebe2d19d95d9918ded1c8/packages/migrator/src/index.ts#L23). It's not yet documented, but it should do what you're suggesting.

[This test](https://github.com/mmkal/slonik-tools/blob/8d7c4a2110db0caed64ebe2d19d95d9918ded1c8/packages/migrator/test/transaction.test.ts#L10-L32) shows an example usage.

**Comment by t3hmrman** [comment]
Thanks @mmkal -- I've been getting along just fine with migrator by using the `BEGIN` and `COMMIT`, and will switch to using `singleTransaction` -- have used migrator on a couple of projects now and it's fantastic, thanks for all the hard work!
