### ISSUE TITLE
Error: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by master-chu** [mmkal/slonik-tools#295]
Hello, 

When using `@slonik/migrator` on version `0.8.0`, calling `node migrate up` throws the error `Error: Cannot read property 'query' of undefined`.

To fix it, I pin `"umzug": "3.0.0-beta.15"` in my package.json instead of the `"3.0.0-beta.12"` which is installed by default given `@slonik/migrator`'s dependency of:

```json
"dependencies": {
    "umzug": "^3.0.0-beta.15"
},
```

I can't tell if this is an incorrectly versioned release from umzug, but in any case, would it perhaps make sense to pin to `-beta.15`?

I'm using Node `v14.16.1`. Below is an example package.json that can reproduce the issue, but let me know if it would be helpful to push up a whole repo:
```json
{
    "name": "migrator-issue",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
        "@slonik/migrator": "^0.8.0",
        "slonik": "^23.8.0"
    }
}
```

**Comment by mmkal** [comment]
@master-chu very helpful, thank you! Seems like it could be a bug in npm, but either way, since it's a prerelease dependency I agree it would make sense to pin. I'll aim to do that in the next few days.

**Comment by mmkal** [comment]
https://github.com/mmkal/slonik-tools/releases/tag/%40slonik%2Fmigrator%400.8.1
