### ISSUE TITLE
Config file doesn't work with .ts imports

### ISSUE THREAD

**Issue by himat** [mmkal/slonik-tools#330]
I tried to run `npx slonik-typegen generate --config typegen.config.ts`
but it failed with `Error: Cannot use import statement outside a module`

It seems like I can only use .js files for the config? 

But I need to use a ts import because I want to load my db connection to pass for the `poolConfig` option.

typegen.config.ts
```
import * as dbConn from "./src/dbConnection";

...
```

So is this not possible to do?

**Comment by mmkal** [comment]
You would have to use something like ts-node to make this work. typegen.config.js would still need to be js, but if you add `require('ts-node/register's)` at the top you should be able to require typescript files after that.
