### ISSUE TITLE
Support of latest slonik major version (26)

### ISSUE THREAD

**Issue by efernandesng** [mmkal/slonik-tools#353]
Currently, `migrator` package has `"slonik": ">= 23.0.0 < 24"` as peerDependecy limiting the accepted versions. I tested `migrator` with `slonik` 16 and it looks to be working properly.

The `typegen` package has `"slonik": ">=23.4.0"` as peerDependecy, but tests fail when slonik 26 is used.

**Comment by mmkal** [comment]
I'll try to cut a new release in the next week or so with the latest slonik. Right now, I'll probably keep the semver ranges fairly narrow until I've implemented some kind of CI testing matrix that doesn't bog down development a ton. I'm glad to hear it works with slonik 16 but that's your call if you want to use such an old package, it's too hard to support that officially.

**Comment by mmkal** [comment]
#357
