### ISSUE TITLE
Release Slonik 26 support?

### ISSUE THREAD

**Issue by bencehornak** [mmkal/slonik-tools#367]
When can we expect a release for `@slonik/migrator` containing support for Slonik 26 (#358)?

Thanks for this amazing open source project, it really helps us a lot!

**Comment by t3hmrman** [comment]
I suspect it's not this easy but a locally `npm link`'d [fork with some minimal changes](https://github.com/t3hmrman/slonik-tools/tree/chore/support-slonik-26) builds without issue for me. All I've done is change the broken `...Type` imports and it looks to be usable.

I've tried running the migrator and it works as well... not sure if it's actually this easy!

**Comment by mmkal** [comment]
@bencehornak released, sorry for the wait. @t3hmrman we can discuss in the PR but slonik 27 will take a little more than just pushing the “go” button!

**Comment by t3hmrman** [comment]
No problem, thanks for taking care of this so quickly @mmkal ! :bow:
