### ISSUE TITLE
`@slonik/typegen` not working on `.sql` files - prettier error

### ISSUE THREAD

**Issue by paambaati** [mmkal/slonik-tools#379]
When running `@slonik/typegen` on a small project, I'm running into an error where the types aren't generated. I'm using `slonik` v28.0.0, `@slonik/typegen` v0.11.3 and Prettier v2.6.1

See https://github.com/paambaati/slonik-typegen-bug-repro for a [short, self-contained, correct example](http://sscce.org/).

I'm seeing this error –

```
Using default pool config - type parsers will not be respected.
Searching for files matching **/*.{ts,sql} in sql/.
Found 19 files and 10 queries.
/Users/me/Projects/slonik-test/sql/slonik-test.ts:10 Describing query failed: error: type with ID 4294867231 does not exist.
Succesfully processed 9 out of 10 queries in files /Users/me/Projects/slonik-test/sql/1-users.sql,/Users/me/Projects/slonik-test/sql/2-organisations.sql,/Users/me/Projects/slonik-test/sql/3-organisation-users.sql,/Users/me/Projects/slonik-test/sql/4-user-groups.sql,/Users/me/Projects/slonik-test/sql/5-user-group-members.sql,/Users/me/Projects/slonik-test/sql/6-collections.sql,/Users/me/Projects/slonik-test/sql/7-shortcuts.sql,/Users/me/Projects/slonik-test/sql/8-collection-managers.sql,/Users/me/Projects/slonik-test/sql/9-link-permissions.sql .
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);
prettier failed to run; Your output might be ugly! Error below:
Expression expected. (76:5)
  74 |
  75 | export const _queryCache = new Map < string, string;
> 76 |     > ();
     |     ^
  77 |
  78 | export const defaultReadFileSync = (filepath: string) => {
  79 |     const cached = _queryCache.get(filepath);

```

**Comment by paambaati** [comment]
CC: @gajus @mmkal

**Comment by janpaepke** [comment]
Would you mind also posting the original source of at least one file you're trying to process?
Because for the sections you posted, prettier is actually right: An Expression IS expected, because the previous line ends with a semicolon.
```
export const _queryCache = new Map < string, string;
> ();
```

You'll get the same error from this code on the prettier playground.
export const _queryCache = new Map < string, string;
> ();

removing the `;` fixes this.

**Comment by paambaati** [comment]
> Would you mind also posting the original source of at least one file you're trying to process?

@janpaepke I've linked it in the parent comment, but in case you missed it, here goes – https://github.com/paambaati/slonik-typegen-bug-repro/tree/main/sql

**Comment by janpaepke** [comment]
Ok so it seems this issue appeared with typescript 4.2.
My guess is it has something to do with this change: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#expanded-uncalled-function-checks.

I think this might be a typescript bug, I'll raise it in ts project later.
For now I'll push a simple workaround, which fixes this.

**Comment by janpaepke** [comment]
Ok researched some more and found it's a feature, not a bug. :D

So the real culprit was that `__filename` was passed into the prettify function, which was transpiled to a js file, so it ended in `.js`.
Apparently if the `fileName` passed into `ts.createSourceFile` ends with `.js` it disables ts features.
Which makes sense but is quite subtle.

Visit this CodeSandbox to see what I mean.
Open Console and play around with the code.

The good news is, that this is an even easier fix: https://github.com/mmkal/slonik-tools/pull/388/files

**Comment by janpaepke** [comment]
Merged and to be released soon.
Thanks @paambaati for the report but most importantly the very well set up debugging repo. This helped greatly getting to the root of this.

**Comment by mmkal** [comment]
Released: https://github.com/mmkal/slonik-tools/releases/tag/%40slonik%2Ftypegen%400.12.2

note that there is a breaking change in this release (see #382)
