### ISSUE TITLE
Typegen error with numeric(x,y) type

### ISSUE THREAD

**Issue by johncsnyder** [mmkal/slonik-tools#415]
Hey 👋  I'm getting an error generating types for queries that contain a column of type `numeric(24,8)` (with the precision and scale specified):

```
❯ npx slonik-typegen generate
Using default pool config - type parsers will not be respected.
Matching files in ./src with pattern **/*.{ts,sql} excluding **/node_modules/**
Searching for files.
Found 3 files matching criteria.
./src/app.ts:47 [!] Extracting types from query failed: TypeError: Cannot read properties of undefined (reading 'typname').
./src/app.ts finished. Processed 0/1 queries.
Finished processing 0/1 queries in 0/3 files.
```

After a bit of digging, I think the issue is here https://github.com/mmkal/slonik-tools/blob/59b34ba98a9362c112e25e6d09d11933510a0140/packages/typegen/src/index.ts#L117 This handles cases like `varchar(16)` but not `numeric(24,8)`.

I believe the fix could look like `if (regtype.match(/\(\d+\)/) || regtype.match(/\(\d+,\d+\)/))`. I've tested that one-liner change locally and seems to work.

---

Platform:
* node 18.11.0
* @slonik/typegen 0.14.2
* slonik 28.2.0

**Comment by mmkal** [comment]
Thanks for the detailed report! Fastest way to get this fixed would be a pull request, with a snapshot test to make sure it doesn't accidentally regress. You could add an like of sql to somewhere in options.test.ts which is kinda a kitchen sink of Postgres features and their outputs, then run `yarn test options.test.ts -u`. 

Also, I think I'd probably go for a single regex that also covers three arguments in case that's possible, like `/\([\d, ])/` maybe?

If you don't feel like opening a PR, I'll try to get to this when I can but can't promise any particular timeline.

**Comment by johncsnyder** [comment]
Yeah sure, I'd be happy to contribute :)

>Also, I think I'd probably go for a single regex that also covers three arguments in case that's possible, like /\([\d, ])/ maybe?

Yes sounds good

**Comment by johncsnyder** [comment]
@mmkal I've opened a PR, including an update to the snapshot test you suggested. Let me know if you've got any other comments 🙏 

Thanks for the quick response on this!
