### ISSUE TITLE
Update `pgsql-ast-parser` to support `SKIP LOCKED` and `NOWAIT` clauses

### ISSUE THREAD

**Issue by arajski** [mmkal/slonik-tools#419]
Hi! 
`pgsql-ast-parser` is now supporting `SKIP LOCKED` and `NOWAIT` clauses in the latest release [11.1.0](https://github.com/oguimbal/pgsql-ast-parser/releases/tag/11.1.0)
It would be amazing if typegen was updated to use this version. 
I'd be keen to write some tests for it if required.

**Comment by mmkal** [comment]
fixed by #420
released in 0.15.0: [npm](https://www.npmjs.com/package/@slonik/typegen/v/0.15.0) [github](https://github.com/mmkal/slonik-tools/releases/tag/%40slonik%2Ftypegen%400.15.0)
