### ISSUE TITLE
Dependency issues in @pgkit/client, @pgkit/migrator, and @pgkit/migra

### ISSUE THREAD

**Issue by dlmarvin** [mmkal/slonik-tools#423]
The @pgkit/client module is missing a dependency on pgsql-ast-parser.
```
// From packages/client/src/naming.ts
import {parse} from 'pgsql-ast-parser'
```

Invalid dependency versions causing npm install of @pgkit/migrator and @pgkit/migra to fail.
```
npm install --save-dev @pgkit/migrator

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @pgkit/migra@^0.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

```
npm install --save-dev @pgkit/migra

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @pgkit/schemainspect@^0.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by mmkal** [comment]
Thanks, I'll take a look. I just want to flag, the pgkit packages are very new, so I hope you'll be patient if there are some initial problems like this! See the note in the root readme of this repo.

**Comment by dlmarvin** [comment]
Thanks for the quick response and fix, I know that this is all new I was just eager to try it out.

**Comment by dlmarvin** [comment]
@mmkal Hey is there anywhere I can ask you questions for help? I'm running into some other issues with the migrator and don't want to spam you with github issues.

**Comment by mmkal** [comment]
Do you have discord? I'm the same username there or I think you can add me via this link https://discord.gg/g9PQnUVf
