### ISSUE TITLE
@slonik/typegen + slonik-interceptor-field-name-transformation

### ISSUE THREAD

**Issue by moltar** [mmkal/slonik-tools#72]
It seems like the generator is not respecting the transformation from the `slonik-interceptor-field-name-transformation` interceptor and every key is still underscore cased.

Would it be possible to support key transformations?

**Comment by trungtin** [comment]
To fix this you have to fork both `@slonik/typegen` and `slonik-interceptor-field-name-transformation`

Another way is to use `patch-package` and modify the node_modules directly:
- replace `afterQueryExecution ` with `beforeQueryResult ` here https://github.com/mmkal/slonik-tools/blob/d70183ccd42f420da584d973c755d0afeea9cc9c/packages/typegen/src/index.ts#L175
- mutate the `fields` variable around here (node_modules compiled code may look differently ), it has the shape of `{ dataTypeId: number, name: string }[]`. Change the `name` to camel_case (try to reuse the `formatted` property) ... https://github.com/gajus/slonik-interceptor-field-name-transformation/blob/5ac0c079c65de7c25a7a1bab7176b242343b240f/src/factories/createFieldNameTransformationInterceptor.js#L38

**Comment by mmkal** [comment]
@moltar do you have a small reproduction for this? I don't use the library, and am a little unclear on what the purpose is. But it should be possible at least to allow some sort of custom transformation of typescript keys, without patching the other library.

**Comment by mmkal** [comment]
No plans to support this out of the box. I don't really see the value in changing the casing of db columns. However if you do want/need to use it or something similar, you can now [modify types before they are written](https://github.com/mmkal/slonik-tools/tree/master/packages/typegen#modifying-types), so you could camel-case fields there too to match them up to the runtime results.

**Comment by gajus** [comment]
@moltar Here is an example:

```ts
const typegen = require('@slonik/typegen');
const {
  camelCase,
} = require('lodash');

module.exports.default = {
  writeTypes: (queries) => {
    for (const query of queries) {
      for (const field of query.fields) {
        field.name = camelCase(field.name);
      }
    }

    return typegen.defaults.defaultWriteTypes()(queries);
  },
};

```
