### ISSUE TITLE
@slonik/typegen: feat: extract comments from db columns and use them in the type comments

### ISSUE THREAD

**Issue by moltar** [mmkal/slonik-tools#73]
It is possible to add comments to tables and columns in PostgreSQL.

Would be great to be able to read that information, and use it as part of the generated type.

**Comment by mmkal** [comment]
Right now the type metadata comes from the node-pg library which doesn't seem to provide comments, unless you know of a way to tell it to?

**Comment by mmkal** [comment]
Comments will now be translated to jsdoc comments: https://github.com/mmkal/slonik-tools/tree/master/packages/typegen#usage
