### ISSUE TITLE
@slonik/typegen is broken starting from slonik@21.0.0

### ISSUE THREAD

**Issue by moltar** [mmkal/slonik-tools#80]
All types are generated as `unknown` starting from `slonik@21.0.0`.

**Comment by trungtin** [comment]
`slonik@21.0.0` introduce a breaking change by renaming `dataTypeID` to `dataTypeId`.

You could either fork this project or using `patchpackage` to modify `node_modules/@slonik/typegen/dist/index.js`

**Comment by mmkal** [comment]
@moltar thanks for reporting and thanks @trungtin for the workaround - I'll take a look at pushing a new version with this fix. Just a note - in general these packages won't be able to keep perfectly up-to-date with breaking slonik changes, so do take note of the supported slonik versions in `peerDependencies` (slonik is only supported `<20` right now): https://github.com/mmkal/slonik-tools/blob/d70183ccd42f420da584d973c755d0afeea9cc9c/packages/typegen/package.json#L22

**Comment by mmkal** [comment]
Fixed - released in 0.3.0.
